#!/bin/python3
from itertools import count
from turtle import hideturtle
import requests
import time
import json
import pyfiglet
#This Programe used to get ip reoutation from 3 threat intel using API's (VirusTotal,AbuseIpDb ,XForce)
def main():
            print("Made BY : Mohamed Khamis")
#print the programe header
            print("-" *65+"\n")
            print(pyfiglet.figlet_format("               Reputation Checker"))
            print("-" *65+"\n")
#VirusTotal , AbuseIpDp , XForce API's
            API_VT="Your Virustotal API"
            API_AB="Your AbuseIpDb API"
            API_XF="Authorization KEY generated by your XForce key & password "
#VirusTotal , AbuseIpDp , XForce url's
            url_VT= "VirusTotal URL"
            url_AB= "AbuseIpDb URL"
            url_xf= "XForce URL"
#VirusTotal , AbuseIpDp , XForce headers
            headers_VT = {"Accept": "application/json","x-apikey": API_VT}
            headers_AB = {'Accept': 'application/json','Key': API_AB}
            headers_xf = {'accept': 'application/json','Authorization': API_XF }

            #ip you want to check
            ip=str(input("Enter IP You Want To Check : "))  

            #AbuseIp get respons in json formate------------
            querystring = {'ipAddress': ip,'maxAgeInDays': '30'}#to get last 30 days report 
            response_AB = requests.request(method='GET', url=url_AB, headers=headers_AB, params=querystring)
            decodedResponse = json.loads(response_AB.text)
            #to get specific attribute in json file 
            domain=decodedResponse["data"]["domain"]#domain name
            score=decodedResponse["data"]["abuseConfidenceScore"]#Abuse score

            #xforce get response on json formate------------
            urlxf=url_xf+ip
            response_xf = requests.get(urlxf, headers=headers_xf)
            jresponse_xf=json.loads(response_xf.text)
            #to get specific attribute in json file 
            history=len(jresponse_xf['history'])# to get last updated report to print last XForce score number
            countryxf=jresponse_xf['history'][history-1]['geo']['country']#country name
            scorexf=jresponse_xf['history'][history-1]['score']#xforce score
            
            #virustotal get respons in json formate----------
            urlvt = url_VT+ip 
            response_VT = requests.get(urlvt, headers=headers_VT)
            jresponse_VT=json.loads(response_VT.text)
            #to get specific attribute in json file 
            lar=jresponse_VT["data"]["attributes"]["last_analysis_results"] # used to count VirusTotal score

            #to count malicious and print vt total score
            total_vendors=0
            total_detect=0
            for i in lar:
                total_vendors+=1
                if lar[i]["category"]=="malicious" or lar[i]["category"]=="suspicious":
                    total_detect+=1
            #printing ip reputation
            print("\n"+"[vt:%s / %s ,Abuseip:%s ,XForce: %s ,country:%s ,domani:%s]"%(total_detect,total_vendors,score,scorexf,countryxf,domain))
            #to restart the programe and not to exite
            restart=input("\n"+"-"*65+"\n\nwant to continue .. Y/N: ").lower()
            if restart == 'y':
                main()
            else:
                exit()
main()
